import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "./components/header";
import MainSection from "./components/mainSection";
import Revolution from "./components/revolution";
import EvolvLayer from "./components/evolvLayer";
import Immersive from "./components/immersive";
import FutureReady from "./components/futureReady";
import RoadmapSection from "./components/roadmap";
import Fans from "./components/fans-collectors";
import Footer from "./components/footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div className="bg-background-primaryDark overflow-hidden">
      <Head>
        <title>Evolv.art</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-grains">
        <div className="bg-custom1">
          <Header />
          <MainSection />
        </div>
        <div className="-mt-[222px] md:-mt-[167px]">
          <div className="bg-zigzag bg-center md:bg-cover relative bg-no-repeat" >
              <Revolution/>
          </div>
        </div>
        <EvolvLayer/>
        <Immersive/>
        <FutureReady/>
        <RoadmapSection/>
        <Fans/>
      </main>
      <Footer/>
    </div>
  );
}